---
version: '3.3'

services:
  web:
    container_name: ff_dev_web
    build:
      context: .
    #user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    ports:
      - '127.0.0.1:8080:80'
    #volumes:
    #  - $PWD/app:/var/www/html
    networks:
      - ff_dev_net

  postgres:
    container_name: ff_dev_postgres
    image: postgres:15.0
    #user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    environment:
      PGPASSWORD: password
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - '127.0.0.1:5532:5432'
    volumes:
      - app-postgres-data:/var/lib/postgresql/data
    networks:
      - ff_dev_net

  postgres-test:
    container_name: ff_dev_postgres_test
    image: postgres:15.0
    environment:
      PGPASSWORD: password
      POSTGRES_DB: appdb_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '127.0.0.1:5632:5432'
    volumes:
      - app-postgres-test-data:/var/lib/postgresql/data
    networks:
      - ff_dev_net


  redis:
    container_name: ff_dev_redis
    image: redis:6.2
    ports:
      - '127.0.0.1:6479:6379'
    volumes:
      - app-redis-data:/var/lib/redis/data
    networks:
      - ff_dev_net

networks:
  ff_dev_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.1.0/24

volumes:
  app-postgres-data:
  app-postgres-test-data:
  app-redis-data:
