---
version: '3.3'

services:
  web:
    container_name: app_web
    build:
      context: .
    #user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - $PWD/app:/var/www/html
    networks:
      - laravel-net

  postgres:
    container_name: app_postgres
    image: postgres:15.0
    #user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    environment:
      PGPASSWORD: password
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - '127.0.0.1:5433:5432'
    volumes:
      - $PWD/postgres-data:/var/lib/postgresql/data
    networks:
      - laravel-net

  redis:
    container_name: app_redis
    image: redis:6.2
    ports:
      - '127.0.0.1:6380:6379'
    volumes:
      - $PWD/redis-data:/var/lib/redis/data
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge
